from services.babel_service import validate_with_babel

def validate_component(code):
    """
    Validate the React component generated by the AI.
    """

    # Check empty response
    if not code or not code.strip():
        return False, "Error: Empty response from AI."

    # Root component must follow AuraGen contract
    if "const Component" not in code:
        return False, "Error: Root component must be named Component."

    # Basic JSX check
    if "<" not in code or ">" not in code:
        return False, "Error: JSX code not found."

    # Markdown is not allowed
    if "```" in code:
        return False, "Error: Remove markdown formatting."

    # Imports are not allowed
    if "import " in code:
        return False, "Error: Import statements are not allowed."

    # Exports are not allowed
    if "export " in code:
        return False, "Error: Export statements are not allowed."

    # Check balanced curly braces
    if code.count("{") != code.count("}"):
        return False, "Error: Unbalanced braces."

    # Check balanced parentheses
    if code.count("(") != code.count(")"):
        return False, "Error: Unbalanced parentheses."

    # Babel AST validation
    babel_result = validate_with_babel(code)

    if not babel_result["valid"]:
        return False, f"Babel validation failed: {babel_result['message']}"

    return True, "React component is valid."


if __name__ == "__main__":
    print("✅ Validator is running")