import re

from services.babel_service import validate_with_babel


def validate_component(code: str) -> tuple[bool, str]:
    """
    Validate the React component generated by the AI.
    """

    # ==========================================================
    # Empty Response
    # ==========================================================

    if not code or not code.strip():
        return False, "Error: Empty response from AI."

    code = code.strip()

    # ==========================================================
    # Remove Markdown Fences
    # ==========================================================

    code = re.sub(r"^```(?:jsx|javascript|js|tsx|ts)?", "", code)
    code = re.sub(r"```$", "", code)
    code = code.strip()

    # ==========================================================
    # Root Component Validation
    # ==========================================================

    if not (
        re.search(r"const\s+Component\s*=", code)
        or re.search(r"function\s+Component\s*\(", code)
    ):
        return (
            False,
            "Error: Root component must be named Component.",
        )

    # ==========================================================
    # Return Statement
    # ==========================================================

    if "return" not in code:
        return (
            False,
            "Error: JSX return statement not found.",
        )

    # ==========================================================
    # Import Statements
    # ==========================================================

    if re.search(
        r"^\s*import\s",
        code,
        re.MULTILINE,
    ):
        return (
            False,
            "Error: Import statements are not allowed.",
        )

    # ==========================================================
    # Export Statements
    # ==========================================================

    if re.search(
        r"^\s*export\s",
        code,
        re.MULTILINE,
    ):
        return (
            False,
            "Error: Export statements are not allowed.",
        )

    # ==========================================================
    # Balanced Braces
    # ==========================================================

    if code.count("{") != code.count("}"):
        return (
            False,
            "Error: Unbalanced braces.",
        )

    # ==========================================================
    # Balanced Parentheses
    # ==========================================================

    if code.count("(") != code.count(")"):
        return (
            False,
            "Error: Unbalanced parentheses.",
        )

    # ==========================================================
    # Babel AST Validation
    # ==========================================================

    babel_result = validate_with_babel(code)

    if not babel_result.get("valid", False):
        return (
            False,
            "Babel validation failed: "
            f"{babel_result.get('message', 'Unknown error')}",
        )

    # ==========================================================
    # Success
    # ==========================================================

    return (
        True,
        "React component is valid.",
    )


if __name__ == "__main__":
    print("✅ Validator Running...")