def validate_component(code):
    """
    Validate the React component generated by the AI.
    """

    # Check if response is empty
    if not code.strip():
        return False, "Error: Empty response from AI."

    # Check if it contains a React component
    if "function" not in code and "const" not in code:
        return False, "Error: React component not found."

    # Check if JSX exists
    if "<div" not in code:
        return False, "Error: JSX code not found."

    # Check if AI returned markdown
    if "```" in code:
        return False, "Error: Remove markdown formatting."

    # Check for export default
    if "export default" not in code:
        return False, "Missing export default."

    # Check for return statement
    if "return" not in code:
        return False, "Missing return statement."

    # Check balanced curly braces
    if code.count("{") != code.count("}"):
        return False, "Unbalanced braces."

    # Check balanced parentheses
    if code.count("(") != code.count(")"):
        return False, "Unbalanced parentheses."

    return True, "React component is valid."

if __name__ == "__main__":
    print("✅ Validator is running")
